### ISSUE TITLE
More usage examples in the README.md

### ISSUE THREAD

**Issue by EmptyJay** [xypwn/scadqr#10]
I just spent 15 minutes trying to generate a WiFi QR code. After trying many, many different things and completely failing to find anything via Google, I discovered the problem.

The output of the qr_wifi() **function** needs to be fed to the qr() or qr_custom() **module**. I'm still very much a novice OpenSCAD user, so the distinction did not mean anything to me. It's only now after figuring it out that I see API.md does include this detail.

Perhaps a line or two about it in the main README.md will help save some people time and frustration.

"The output of the functions (qr_wifi, qi_phone_call, etc) needs to be used as the parameter to the qr() or qr_custom() call. For example: qr(qr_wifi(SSID, PSK, auth, hidden))"

**Comment by xypwn** [comment]
Thanks for the feedback!

I added a simple Wi-Fi example and hopefully made it a bit clearer. Let me know what you think!

**Comment by EmptyJay** [comment]
Perfect. Thank you! 

Funny that I've seen your library in 2 different places in the past day. Hackaday and Reddit for the hotel project.

**Comment by xypwn** [comment]
Wow! I wasn't even aware of the Hackaday post! I was wondering why I was getting so many stars all of a sudden 😂

I'm really flattered though!
