### ISSUE TITLE
suggestion: stencil mode

### ISSUE THREAD

**Issue by SimplifyAndAddCoffee** [xypwn/scadqr#3]
might it be possible to extend this library to support making QR stencils? e.g. link together isolated squares on a second layer?

**Comment by xypwn** [comment]
Hi, thanks for your issue.
This would require an algorithm to determine the most effective placement of connection pieces for isolated areas, which seems like an exceedingly complex task, especially given the limited possibilities of the SCAD programming language.

One possibility, if this is for a personal project, would be to simply generate a grid mesh that connects ALL the pixels with a small bridge.
