### ISSUE TITLE
Incompatible with 2024+ versions of OpenSCAD (Compilation aborted by exception: std::get: wrong index for variant)

### ISSUE THREAD

**Issue by dan-p3rry** [xypwn/scadqr#4]
Hi,
Running both demo.scad and my own code, I get the compilation error in the title.  I'm guessing here, because I wasn't able to fix it, but the syntax for function qr() looks very strange to me --> missing braces after qr(all_the_arguments), but braces exist after qr_custom(all_the_arguments){}.
Dan

module qr(message, error_correction="M", width=100, height=100, thickness=1, center=false, mask_pattern=0, encoding="UTF-8") 
    qr_custom(message, error_correction, width, height, thickness, center, mask_pattern, encoding) {
        _qr_default_module();
        _qr_default_position_pattern();
        _qr_default_alignment_pattern();
}

**Comment by xypwn** [comment]
Hi,
the error you are getting is a C++ error, not an OpenSCAD error ("exception" and "std::get" are C++ things that don't exist in OpenSCAD). This means the bug must be within the SCAD compiler your version of OpenSCAD uses, and not my library. Additionally, I have some tests set up, which I run before every commit to make sure the library actually still functions properly; and it did on my version of OpenSCAD (2021.01).
The fix that would most likely work for you would be to **upgrade your version of OpenSCAD to the latest version**.
Additionally, however, it would also be great if you could tell me the version you encountered this bug on, so I can maybe come up with a workaround if possible.

Regarding the syntax:
`module` means it's a declaration. The *block* following `qr(arguments)` is the body of the module. That means if you have only a single expression following (in my case a call to `qr_custom`), that will be the module's body (I use indentation in the source code to make that clear to the reader).
This is by far not the most extreme example. If you look at [line 461](https://github.com/xypwn/scadqr/blob/main/qr.scad#L461), for example, you can see how I am chaining many nested let expressions and ternary operators, which yields a single expression (required for `function` declarations).
My syntax might be a bit unconventional, but I had to make up some of my own conventions to deal with the complexity of generating QR codes in a language that is barely even made for programming, while still keeping the code somewhat readable (at least to myself).

**Comment by dan-p3rry** [comment]
Thanks for the code explanation and the detailed response.  I saw the error
in recent builds (one from last month,  and one I just downloaded a few
days ago.  These recent builds are important because they have dramatic
improvements in the rendering engine.  Old versions of your code work with
the new OpenSCAD versions.
Thanks again,
Dan

**Comment by xypwn** [comment]
I didn't realize you were referring to the more recent builds! It's very important to me that the library works with all modern versions. I installed 2024.02.22 and can replicate the bug. I'll open an issue with OpenSCAD regarding the bug, and if possible try to narrow down the problem to find a workaround.
Thank you for bringing this problem to my attention :)

**Comment by xypwn** [comment]
Turns out the culprit was a bug in the builtin `search` function. I completely stopped using this function for newer versions, which should have the additional benefit of speeding up generation on newer versions.
Thanks for reporting the issue and please let me know if you find any further problems!

**Comment by dan-p3rry** [comment]
Thanks for the quick fix.  The reason I was downloading a new version is because someone using this model [https://makerworld.com/en/models/64195](url) reported a bug, the output didn't match the input.  I will file a new issue.

**Comment by xypwn** [comment]
https://github.com/openscad/openscad/issues/5017
