### ISSUE TITLE
[Feature Request] Events

### ISSUE THREAD

**Issue by adriangalilea** [xypwn/scadqr#7]
Hey, just came across this library, many thanks for sharing, I was testing the "standard" options for qr info and was testing the library with an event, I tried manually inputting the text like:

```
// Concatenate the event details into a single line string
event_text = concat(
    "BEGIN:VEVENT\n",
    "SUMMARY:Meeting\n",
    "DTSTART:20240620T150000Z\n",
    "DTEND:20240620T160000Z\n",
    "LOCATION:Casa de Adrian\n",
    "DESCRIPTION:Comida\n",
    "END:VEVENT"
);

// Call the module with the concatenated text
qr_with_base(event_text);
```

But it failed, then I inspected the api.md and noticed several options but missing the event one, may be cool to add it, I can take a look if you want and PR.

Excerpt of ChatGPT convo explaining how QR events work:

To create a QR code that embeds a calendar event, you need to follow a specific format for the data string. The format for embedding calendar event details in a QR code is as follows:

```
BEGIN:VEVENT
SUMMARY:<Event Title>
DTSTART:<Start Date and Time>
DTEND:<End Date and Time>
LOCATION:<Event Location>
DESCRIPTION:<Event Description>
END:VEVENT
```

Here is a detailed breakdown of the fields:

	•	SUMMARY: The title of the event.
	•	DTSTART: The start date and time of the event in the format YYYYMMDDTHHMMSSZ.
	•	DTEND: The end date and time of the event in the format YYYYMMDDTHHMMSSZ.
	•	LOCATION: The location of the event.
	•	DESCRIPTION: A description of the event.

Example:

For an event with the title “Meeting”, starting on June 20, 2024, at 15:00 UTC, ending on June 20, 2024, at 16:00 UTC, located at “Office”, with the description “Quarterly business meeting”, the string would be:

```
BEGIN:VEVENT
SUMMARY:Meeting
DTSTART:20240620T150000Z
DTEND:20240620T160000Z
LOCATION:Office
DESCRIPTION:Quarterly business meeting
END:VEVENT
```

**Comment by xypwn** [comment]
Sounds like a useful feature. I'll implement it when I have time.

Although, I'm kind of surprised your code didn't work. In what way did it fail?

**Comment by adriangalilea** [comment]
@xypwn

When scanned it displayed some weird stuff on my iphone, maybe it's just incompatible, or something odd, haven't double checked

Thanks

**Comment by xypwn** [comment]
Did you check whether your VEVENT text was valid at all? I think it has to be wrapped in a VCALENDAR. Not sure though, I haven't really worked with the format yet.

**Comment by adriangalilea** [comment]
Hey @xypwn, no I haven't used it ever before, I just shared what chatGPT suggested so there could be mistakes for sure.

I just tried again,

```python
import qrcode

ical_content = """
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Your Organization//NONSGML v1.0//EN
BEGIN:VEVENT
UID:unique-identifier
DTSTAMP:20240626T090000Z
DTSTART:20240626T100000Z
DTEND:20240626T110000Z
SUMMARY:Event Title
DESCRIPTION:Event Description
LOCATION:Event Location
END:VEVENT
END:VCALENDAR
"""

qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data(ical_content)
qr.make(fit=True)

img = qr.make_image(fill='black', back_color='white')
img_path = "/mnt/data/event_qr.png"
img.save(img_path)
```

This code generated:

![image](https://github.com/xypwn/scadqr/assets/90320947/9e5f4f91-f6f2-4516-8662-92fd042d710e)

Which seems to work.

**Comment by xypwn** [comment]
Great, the same text should work in ScadQR too then

**Comment by adriangalilea** [comment]
I tried the same text and failed tho,  maybe I just don't know how to input the multi-line properly.

```
include <qr.scad>

// Parameters
base_thickness = 2; // Thickness of the base layer
base_margin = 5;    // Margin around the QR code

module qr_with_base(text) {
    // Set QR code dimensions
    qr_width = 100;
    qr_height = 100;

    // Calculate the base size based on QR code dimensions
    base_size = [qr_width + 2 * base_margin, qr_height + 2 * base_margin, base_thickness];

    // Create the base
    color("yellow") {
        cube(base_size, center = true);
    }

    // Position the QR code on top of the base
    translate([0, 0, base_thickness / 2])
        color("black") {
            qr(text, width=qr_width, height=qr_height, center=true);
        }
}

// Concatenate the event details into a single line string
event_text = concat(
    "BEGIN:VCALENDAR\\n",
    "VERSION:2.0\\n",
    "PRODID:-//Your Organization//NONSGML v1.0//EN\\n",
    "BEGIN:VEVENT\\n",
    "SUMMARY:Meeting\\n",
    "DTSTART:20240620T150000Z\\n",
    "DTEND:20240620T160000Z\\n",
    "LOCATION:Casa de Adrian\\n",
    "DESCRIPTION:Comida\\n",
    "END:VEVENT\\n",
    "END:VCALENDAR"
);

// Call the module with the concatenated text
qr_with_base(event_text);

```
This fails

**Comment by xypwn** [comment]
The newline escape character is "\n". "\\\n" just produces "\n" as text.

**Comment by adriangalilea** [comment]
```
include <qr.scad>

// Parameters
base_thickness = 2; // Thickness of the base layer
base_margin = 5;    // Margin around the QR code

module qr_with_base(text) {
    // Set QR code dimensions
    qr_width = 100;
    qr_height = 100;

    // Calculate the base size based on QR code dimensions
    base_size = [qr_width + 2 * base_margin, qr_height + 2 * base_margin, base_thickness];

    // Create the base
    color("yellow") {
        cube(base_size, center = true);
    }

    // Position the QR code on top of the base
    translate([0, 0, base_thickness / 2])
        color("black") {
            qr(text, width=qr_width, height=qr_height, center=true);
        }
}

// Multiline event text
event_text = "BEGIN:VCALENDAR\n\
VERSION:2.0\n\
PRODID:-//Your Organization//NONSGML v1.0//EN\n\
BEGIN:VEVENT\n\
SUMMARY:Meeting\n\
DTSTART:20240620T150000Z\n\
DTEND:20240620T160000Z\n\
LOCATION:Casa de Adrian\n\
DESCRIPTION:Comida\n\
END:VEVENT\n\
END:VCALENDAR";

// Call the module with the concatenated text
qr_with_base(event_text);

```

This worked

**Comment by adriangalilea** [comment]
I'd say it would be better to have it on the API, right?

**Comment by xypwn** [comment]
I might implement it when I find the time, which is why I'll leave this issue open for now

**Comment by xypwn** [comment]
Turns out it was pretty simple, here you go :)

**Comment by xypwn** [comment]
Let me know if you encounter any issues using this
